# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AFT_LN_mcmc <- function(Wmat, wUInf, wLUeq, c0Inf, Xmat, hyperP, mcmcP, startValues, n_burnin, n_sample, thin) {
    .Call(`_AFTTV_AFT_LN_mcmc`, Wmat, wUInf, wLUeq, c0Inf, Xmat, hyperP, mcmcP, startValues, n_burnin, n_sample, thin)
}

AFTtv_LN_rjmcmc <- function(Ymat, yUInf, yLUeq, c0Inf, Xmat, Xvec_tv, prior_list_num, hyper_list, tuning_list, start_list, knots_init, n_burnin, n_sample, thin) {
    .Call(`_AFTTV_AFTtv_LN_rjmcmc`, Ymat, yUInf, yLUeq, c0Inf, Xmat, Xvec_tv, prior_list_num, hyper_list, tuning_list, start_list, knots_init, n_burnin, n_sample, thin)
}

AFTtv_LN_mcmc <- function(Ymat, yUInf, yLUeq, c0Inf, Xmat, Xvec_tv, hyperP, beta_prop_var, btv_prop_var, mu_prop_var, sigSq_prop_var, knots_init, startValues, n_burnin, n_sample, thin) {
    .Call(`_AFTTV_AFTtv_LN_mcmc`, Ymat, yUInf, yLUeq, c0Inf, Xmat, Xvec_tv, hyperP, beta_prop_var, btv_prop_var, mu_prop_var, sigSq_prop_var, knots_init, startValues, n_burnin, n_sample, thin)
}

dmvnrm_arma <- function(x, mean, var, cholinvSigma_sub, logd = 1L) {
    .Call(`_AFTTV_dmvnrm_arma`, x, mean, var, cholinvSigma_sub, logd)
}

Vx_pw <- function(T, Xmat, beta, Xvec_tv, beta_tv, knots, log_out) {
    .Call(`_AFTTV_Vx_pw`, T, Xmat, beta, Xvec_tv, beta_tv, knots, log_out)
}

