# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BAFTtvLTmcmc <- function(Wmat, wUInf, c0Inf, Xmat, hyperP, mcmcP, startValues, n_burnin, n_sample, thin) {
    .Call(`_AFTTV_BAFTtvLTmcmc`, Wmat, wUInf, c0Inf, Xmat, hyperP, mcmcP, startValues, n_burnin, n_sample, thin)
}

